// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int over = 0;
		int under = 0;
		for (int i = 0; i < N;i++){
			double rand = Math.random();
			if (rand > 0.5){
				over++;
			}
			else{
				under++;
			}
			System.out.println("> 0.5:   " + over + " times");
			System.out.println("<= 0.5:   " + under + " times");

		}

	}
}
